/** EGEMED Opaca — 28 rozet kataloğu (çekirdek BadgeDef motoru ile değerlendirilir). */

import type { BadgeContext, BadgeDef } from "@egemed/gamification-core";
import type { OpacaStats } from "./stats";
import { OPACA_RULES } from "./rules";

export type OpacaBadgeContext = BadgeContext;

const topic =
  (id: string, max: number): ((s: OpacaStats) => { value: number; max: number }) =>
  (s) => ({ value: s.topicCorrect[id] ?? 0, max });

export const OPACA_BADGES: BadgeDef<OpacaStats, OpacaBadgeContext>[] = [
  {
    id: "sharp-eye-1",
    category: "skill",
    icon: "Target",
    name: "Keskin Göz",
    tier: "bronze",
    description: `Değerlendirmede ${OPACA_RULES.badges.sharpEye[0]} isabetli lokalizasyon.`,
    rule: "10 isabet",
    studyKey: "technique.systematic",
    progress: (s) => ({ value: s.localizationHits, max: OPACA_RULES.badges.sharpEye[0] }),
  },
  {
    id: "sharp-eye-2",
    category: "skill",
    icon: "Target",
    name: "Keskin Göz",
    tier: "silver",
    description: `Değerlendirmede ${OPACA_RULES.badges.sharpEye[1]} isabetli lokalizasyon.`,
    rule: "25 isabet",
    studyKey: "technique.systematic",
    progress: (s) => ({ value: s.localizationHits, max: OPACA_RULES.badges.sharpEye[1] }),
  },
  {
    id: "sharp-eye-3",
    category: "skill",
    icon: "Target",
    name: "Keskin Göz",
    tier: "gold",
    description: `Değerlendirmede ${OPACA_RULES.badges.sharpEye[2]} isabetli lokalizasyon.`,
    rule: "50 isabet",
    studyKey: "technique.systematic",
    progress: (s) => ({ value: s.localizationHits, max: OPACA_RULES.badges.sharpEye[2] }),
  },
  {
    id: "systematic",
    category: "skill",
    icon: "Scan",
    name: "Sistematik Okuyucu",
    description: "Bir vakada ABCDE sırasını eksiksiz izle.",
    rule: "1 tam ABCDE",
    studyKey: "technique.systematic",
    progress: (s) => ({ value: s.abcdeCompleteCount, max: 1 }),
  },
  {
    id: "film-quality",
    category: "skill",
    icon: "Film",
    name: "Film Kalitesi",
    description: `${OPACA_RULES.badges.filmQuality} vakada film kalitesi sorusunu doğru yanıtla.`,
    rule: "10 doğru",
    studyKey: "technique.projection",
    progress: (s) => ({ value: s.qualityCorrect, max: OPACA_RULES.badges.filmQuality }),
  },
  {
    id: "fast-accurate",
    category: "skill",
    icon: "Clock",
    name: "Hızlı ve Doğru",
    description: "Süre sınırının yarısında 90+ puan.",
    rule: "90+ · yarı süre",
    progress: (s) => ({ value: s.fastPerfectCount, max: 1 }),
  },
  {
    id: "interpreter",
    category: "skill",
    icon: "Doc",
    name: "Klinik Yorumcu",
    description: `${OPACA_RULES.badges.interpreter} vakada klinik yorum sorusunu doğru yanıtla.`,
    rule: "10 doğru",
    progress: (s) => ({ value: s.interpretationCorrect, max: OPACA_RULES.badges.interpreter }),
  },
  {
    id: "pleura",
    category: "topic",
    icon: "Lungs",
    name: "Plevra Dedektifi",
    description: `${OPACA_RULES.badges.pleura} pnömotoraks/efüzyon vakasını doğru tanı.`,
    rule: "5 vaka",
    studyKey: "finding.pneumothorax",
    progress: topic("pleura", OPACA_RULES.badges.pleura),
  },
  {
    id: "cardiac",
    category: "topic",
    icon: "Heart",
    name: "Kalp Gölgesi",
    description: `${OPACA_RULES.badges.cardiac} kardiyomegali vakasını doğru tanı.`,
    rule: "5 vaka",
    studyKey: "finding.cardiomegaly",
    progress: topic("cardiac", OPACA_RULES.badges.cardiac),
  },
  {
    id: "nodule",
    category: "topic",
    icon: "Brain",
    name: "Nodül Avcısı",
    description: `${OPACA_RULES.badges.nodule} nodül/kitle vakasını doğru tanı.`,
    rule: "10 vaka",
    studyKey: "finding.nodule_mass",
    progress: topic("nodule", OPACA_RULES.badges.nodule),
  },
  {
    id: "tb",
    category: "topic",
    icon: "Lungs",
    name: "Tüberküloz Okuru",
    description: `${OPACA_RULES.badges.tb} tüberküloz vakasını doğru tanı.`,
    rule: "10 vaka",
    studyKey: "finding.tuberculosis",
    progress: topic("tb", OPACA_RULES.badges.tb),
  },
  {
    id: "pediatric",
    category: "topic",
    icon: "User",
    name: "Pediatri",
    description: `${OPACA_RULES.badges.pediatric} pediatrik vakayı doğru tanı.`,
    rule: "5 vaka",
    studyKey: "finding.steeple_sign",
    progress: topic("pediatric", OPACA_RULES.badges.pediatric),
  },
  {
    id: "diaphragm",
    category: "topic",
    icon: "Diaphragm",
    name: "Diyafram Bilgesi",
    description: `${OPACA_RULES.badges.diaphragm} diyafram konusu vakasını doğru tanı.`,
    rule: "5 vaka",
    studyKey: "finding.hiatal_hernia",
    progress: topic("diaphragm", OPACA_RULES.badges.diaphragm),
  },
  {
    id: "bone",
    category: "topic",
    icon: "Bone",
    name: "Kemik Gözü",
    description: `${OPACA_RULES.badges.bone} kırık vakasını doğru tanı.`,
    rule: "5 kırık",
    studyKey: "finding.fracture",
    progress: topic("bone", OPACA_RULES.badges.bone),
  },
  {
    id: "vascular",
    category: "topic",
    icon: "Wave",
    name: "Damar Yolu",
    description: `${OPACA_RULES.badges.vascular} pulmoner vasküler vakayı doğru tanı.`,
    rule: "3 vaka",
    studyKey: "finding.westermark_sign",
    progress: topic("vascular", OPACA_RULES.badges.vascular),
  },
  {
    id: "streak-3",
    category: "streak",
    icon: "Flame",
    name: "3 Günlük Seri",
    description: "3 gün üst üste en az bir oturum.",
    rule: "3 gün",
    progress: (s) => ({ value: s.streakLongest, max: OPACA_RULES.badges.streak[0] }),
  },
  {
    id: "streak-7",
    category: "streak",
    icon: "Flame",
    name: "7 Günlük Seri",
    description: "7 gün üst üste en az bir oturum.",
    rule: "7 gün",
    progress: (s) => ({ value: s.streakLongest, max: OPACA_RULES.badges.streak[1] }),
  },
  {
    id: "streak-30",
    category: "streak",
    icon: "Flame",
    name: "Ay Boyu Seri",
    description: "30 gün üst üste en az bir oturum.",
    rule: "30 gün",
    progress: (s) => ({ value: s.streakLongest, max: OPACA_RULES.badges.streak[2] }),
  },
  {
    id: "marathon",
    category: "streak",
    icon: "Chart",
    name: "Maraton",
    description: `${OPACA_RULES.badges.marathon} değerlendirme oturumu tamamla.`,
    rule: "50 oturum",
    progress: (s) => ({ value: s.assessmentCount, max: OPACA_RULES.badges.marathon }),
  },
  {
    id: "explorer",
    category: "learn",
    icon: "Book",
    name: "Öğrenme Kaşifi",
    description: `Öğrenme modunda ${OPACA_RULES.badges.explorerTopics} farklı konu incele.`,
    rule: "10 konu",
    progress: (s) => ({ value: s.learnTopicsCount, max: OPACA_RULES.badges.explorerTopics }),
  },
  {
    id: "ct-explorer",
    category: "learn",
    icon: "Diaphragm",
    name: "BT Kaşifi",
    description: "Bir toraks BT kesit yığınını baştan sona tara.",
    rule: "1 BT serisi",
    studyKey: "ct.axial_anatomy",
    progress: (s) => ({ value: s.ctStacksCompletedCount, max: 1 }),
  },
  {
    id: "practice-grit",
    category: "learn",
    icon: "Graduation",
    name: "Uygulama Azmi",
    description: `Uygulama modunda ${OPACA_RULES.badges.practiceGrit} vaka çöz.`,
    rule: "20 vaka",
    progress: (s) => ({ value: s.practiceCaseTotal, max: OPACA_RULES.badges.practiceGrit }),
  },
  {
    id: "first-step",
    category: "milestone",
    icon: "Chart",
    name: "İlk Adım",
    description: "İlk değerlendirme oturumunu tamamla.",
    rule: "İlk değerlendirme",
    progress: (s) => ({ value: s.assessmentCount, max: 1 }),
  },
  {
    id: "threshold",
    category: "milestone",
    icon: "CheckCircle",
    name: "Eşik Aşıldı",
    description: "Bir değerlendirmede ilk kez 80 ve üzeri puan.",
    rule: "80 puan",
    progress: (s) => ({ value: s.bestAssessmentScore, max: OPACA_RULES.badges.thresholdScore }),
  },
  {
    id: "no-hints",
    category: "milestone",
    icon: "Lightbulb",
    name: "İpucusuz",
    description: `Uygulamada ipucu kullanmadan ${OPACA_RULES.badges.noHintsCaseMin} vakalık oturum.`,
    rule: "İpucusuz oturum",
    progress: (s) => ({ value: s.noHintPracticeSessionCount, max: 1 }),
  },
  {
    id: "perfect",
    category: "milestone",
    icon: "Star",
    name: "Kusursuz Oturum",
    description: "Bir değerlendirmede 100 puan.",
    rule: "100 puan",
    progress: (s) => ({ value: s.perfectSessionCount, max: 1 }),
  },
  {
    id: "podium",
    category: "milestone",
    icon: "Medal",
    name: "Podyum",
    description: "Aylık sıralamada ilk 3'e gir.",
    rule: "Aylık ilk 3",
  },
  {
    id: "all-topics",
    category: "milestone",
    icon: "Trophy",
    name: "Tüm Konular",
    description: "Kütüphanedeki her konuda en az bir doğru.",
    rule: "Tüm konular",
    progress: (s) => ({ value: s.allTopicsCoveredCount, max: s.allTopicsTotal }),
  },
];

/** Rozet kimliği → öğrenme modu çalışma anahtarı (katalogdan türetilir). */
export const STUDY_KEY: Record<string, string> = Object.fromEntries(
  OPACA_BADGES.filter((b) => b.studyKey).map((b) => [b.id, b.studyKey!]),
);
