export {
  audienceCanUseMode,
  audienceOf,
  audienceShowsGamification,
  createSimHost,
  SIM_AUDIENCES,
  VISITOR_LOCK_TEXT,
  type SimAudience,
  isSimulatorId,
  SIMULATOR_IDS,
  type SimChrome,
  type SimGamificationSource,
  type SimGamificationSummary,
  type SimChromeAction,
  type SimChromeChip,
  type SimChromeIcon,
  type SimDispose,
  type SimHost,
  type SimHostEvents,
  type SimHostOptions,
  type SimLearnPort,
  type SimModule,
  type SimModuleLoader,
  type SimMountContext,
  type SimMountOptions,
  type SimMountTarget,
  type SimSessionSource,
  type SimulatorId,
} from "./SimHost";
