export {
  audienceCanUseMode,
  audienceOf,
  audienceShowsGamification,
  createSimHost,
  isSimScreenKey,
  SIM_SCREEN_KEYS,
  SIM_AUDIENCES,
  VISITOR_LOCK_TEXT,
  type SimAudience,
  isSimulatorId,
  SIMULATOR_IDS,
  type SimChrome,
  type SimGamificationSource,
  type SimGamificationSummary,
  type SimChromeAction,
  type SimChromeChip,
  type SimChromeIcon,
  type SimDispose,
  type SimHost,
  type SimHostEvents,
  type SimHostOptions,
  type SimLearnPort,
  type SimLearnRecord,
  type SimModule,
  type SimModuleLoader,
  type SimNavigation,
  type SimScreenKey,
  type SimMountContext,
  type SimRewardsSnapshot,
  type SimRewardsSource,
  type SimMountOptions,
  type SimMountTarget,
  type SimSessionSource,
  type SimulatorId,
} from "./SimHost";
