/**
 * Platform ikon seti (lucide-react, ISC). Kabuk ikonları yalnız buradan alır;
 * tek bağımlılık noktası ve tutarlı çizgi kalınlığı için seçilmiş bir alt küme.
 */
export {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowRight,
  Award,
  BookOpen,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ClipboardList,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileSpreadsheet,
  Filter,
  Flame,
  Gift,
  House,
  Info,
  LayoutDashboard,
  LogOut,
  Medal,
  Menu as MenuIcon,
  MoreHorizontal,
  NotebookPen,
  PauseCircle,
  PlayCircle,
  Plus,
  ScanLine,
  ScrollText,
  Search,
  Settings,
  ShieldCheck,
  Stethoscope,
  Swords,
  Target,
  Trash2,
  Trophy,
  Upload,
  User,
  UserPlus,
  Users,
  X,
} from "lucide-react";
